### ISSUE TITLE
Output shows twice

### ISSUE THREAD

**Issue by zerbons** [tap-format/spec#1]
I have: `"test": "tape ./tests/**/*.js | ./node_modules/.bin/tf-spec"`

but the test is outputed twice. Any ideas?

**Comment by zerbons** [comment]
Or maybe it is intended? This how it looks on a failing case:

```
  example test
    ✖ should have the same length
      at Test.<anonymous> (/home/code/examples/ex.js:38:10)

      actual expected

      2964

    ✔ should have the same length

  Failed Tests: There was 1 failure

    example test
      ✖ should have the same length
        at Test.<anonymous> (/home/code/examples/ex.js:38:10)
  
        actual expected
  
        2964
  

  assertions:  2
  passing:     1
  failing:     1
  duration:    50ms
```

**Comment by scottcorgan** [comment]
It does show twice. Once inline where the test happens and once at the end. This makes more sense when there are more tests.

Do you think it would be helpful to have an option to include or exclude the failures at the end?

**Comment by scottcorgan** [comment]
I'm going to close this for because of inactivity and assumption that this is the expected behavior.

We can continue to discuss a feature/option if this is undesired.
